### ISSUE TITLE
在我的detectron2上出现问题！

### ISSUE THREAD

**Issue by johnenvpath** [freepoet/loss_curve#1]
(base) jwz@jwz-B450M-AORUS-ELITE:~/文档/loss_curve-main$ python d2_loss_visualization.py
Traceback (most recent call last):
  File "d2_loss_visualization.py", line 40, in <module>
    _loss = [j['total_loss'] for j in parsed]
  File "d2_loss_visualization.py", line 40, in <listcomp>
    _loss = [j['total_loss'] for j in parsed]
KeyError: 'total_loss'

json文件节选：
{"data_time": 0.09142254400012462, "fast_rcnn/cls_accuracy": 0.923828125, "fast_rcnn/false_negative": 0.5, "fast_rcnn/fg_cls_accuracy": 0.0, "iteration": 1, "loss_box_reg": 0.0003332309570396319, "loss_cls": 1.9383905529975891, "loss_rpn_cls": 0.42315760254859924, "loss_rpn_loc": 0.14394217915832996, "lr": 0.0002198, "roi_head/num_bg_samples": 509.0, "roi_head/num_fg_samples": 3.0, "rpn/num_neg_anchors": 119.5, "rpn/num_pos_anchors": 34.5, "total_loss": 2.505823565661558}
{"fast_rcnn/cls_accuracy": 0.990234375, "fast_rcnn/false_negative": 1.0, "fast_rcnn/fg_cls_accuracy": 0.0, "iteration": 19, "loss_box_reg": 0.019618598744273186, "loss_cls": 0.15482480078935623, "loss_rpn_cls": 0.4104563742876053, "loss_rpn_loc": 0.017588547430932522, "lr": 0.0038161999999999996, "roi_head/num_bg_samples": 508.5, "roi_head/num_fg_samples": 3.5, "rpn/num_neg_anchors": 250.0, "rpn/num_pos_anchors": 6.0, "total_loss": 0.6406855604145676}
{"data_time": 0.0012474840004870202, "eta_seconds": 52173.578584358365, "iteration": 19, "loss_box_reg": 0.5638786256313324, "loss_cls": 1.030214935541153, "lr": 0.00019981, "num_pos_anchors": 85.0, "time": 0.5798352809997596, "total_loss": 1.5940935611724854}
{"data_time": 0.0013120109997544205, "eta_seconds": 40406.14347896984, "iteration": 39, "loss_box_reg": 0.3749055862426758, "loss_cls": 0.7213437259197235, "lr": 0.00039960999999999995, "num_pos_anchors": 78.5, "time": 0.20950734999996712, "total_loss": 1.0962493121623993}
{"data_time": 0.0013301295002747793, "eta_seconds": 19888.90744295607, "iteration": 59, "loss_box_reg": 0.6108564287424088, "loss_cls": 1.066032588481903, "lr": 0.00059941, "num_pos_anchors": 129.5, "time": 0.18952222000007168, "total_loss": 1.6768890172243118}
{"data_time": 0.0014170375002322544, "eta_seconds": 19648.512132270844, "iteration": 79, "loss_box_reg": 0.44091150164604187, "loss_cls": 0.7830549776554108, "lr": 0.0007992100000000001, "num_pos_anchors": 102.0, "time": 0.19866589200000817, "total_loss": 1.2239664793014526}
{"data_time": 0.0012196064999443479, "eta_seconds": 18822.987804977583, "iteration": 99, "loss_box_reg": 0.5466920137405396, "loss_cls": 0.865629106760025, "lr": 0.00099901, "num_pos_anchors": 104.0, "time": 0.18281077850042493, "total_loss": 1.439560353755951}
{"data_time": 0.0011915239997506433, "eta_seconds": 18703.63989816189, "iteration": 119, "loss_box_reg": 0.3629636764526367, "loss_cls": 0.6837942004203796, "lr": 0.00119881, "num_pos_anchors": 70.0, "time": 0.20147716499968737, "total_loss": 1.0467578768730164}
{"data_time": 0.001184370999908424, "eta_seconds": 18669.221448564487, "iteration": 139, "loss_box_reg": 0.4961654543876648, "loss_cls": 0.9037017226219177, "lr": 0.0013986099999999998, "num_pos_anchors": 142.5, "time": 0.2032256504999168, "total_loss": 1.3874416947364807}
{"data_time": 0.0011394509997444402, "eta_seconds": 18435.741448731824, "iteration": 159, "loss_box_reg": 0.5690023601055145, "loss_cls": 1.019535779953003, "lr": 0.0015984099999999998, "num_pos_anchors": 125.0, "time": 0.19523278099995878, "total_loss": 1.5937065780162811}
{"data_time": 0.0011829825002678263, "eta_seconds": 18563.91137279338, "iteration": 179, "loss_box_reg": 0.6740041077136993, "loss_cls": 0.8417367935180664, "lr": 0.0017982099999999997, "num_pos_anchors": 134.0, "time": 0.2108379804994911, "total_loss": 1.456814706325531}
{"data_time": 0.001187766999919404, "eta_seconds": 18559.777791993383, "iteration": 199, "loss_box_reg": 0.3591661602258682, "loss_cls": 0.6540076732635498, "lr": 0.00199801, "num_pos_anchors": 95.5, "time": 0.20695118149978953, "total_loss": 1.0088445544242859}
{"data_time": 0.0011814150002464885, "eta_seconds": 18466.940089838456, "iteration": 219, "loss_box_reg": 0.45492739975452423, "loss_cls": 0.8239938914775848, "lr": 0.00219781, "num_pos_anchors": 79.0, "time": 0.19989405499973145, "total_loss": 1.278921291232109}
{"data_time": 0.0012012074998892786, "eta_seconds": 18393.115062935467, "iteration": 239, "loss_box_reg": 0.4876404404640198, "loss_cls": 0.9065599143505096, "lr": 0.00239761, "num_pos_anchors": 140.5, "time": 0.1891775779999989, "total_loss": 1.3843374848365784}
{"data_time": 0.001202679500238446, "eta_seconds": 18120.044726901833, "iteration": 259, "loss_box_reg": 0.32038429379463196, "loss_cls": 0.5720987617969513, "lr": 0.00259741, "num_pos_anchors": 69.0, "time": 0.1862900565001837, "total_loss": 0.8924830555915833}
{"data_time": 0.0011739359997591237, "iteration": 270, "loss_box_reg": 0.43847568333148956, "loss_cls": 0.826972633600235, "lr": 0.0027073, "num_pos_anchors": 114.5, "time": 0.19756995850048042, "total_loss": 1.2654483169317245}
{"eta_seconds": 18281.55688571348, "iteration": 271}
{"data_time": 0.22258784899986495, "fast_rcnn/cls_accuracy": 0.0068359375, "fast_rcnn/false_negative": 0.0, "fast_rcnn/fg_cls_accuracy": 0.0, "iteration": 0, "loss_box_reg": 0.00046288667363114655, "loss_cls": 4.09865140914917, "loss_mask": 0.6924939751625061, "loss_rpn_cls": 0.3871974050998688, "loss_rpn_loc": 0.03713538870215416, "lr": 2.5e-06, "mask_rcnn/accuracy": 0.5481049562682216, "mask_rcnn/false_negative": 0.3420479302832244, "mask_rcnn/false_positive": 0.607032967032967, "roi_head/num_bg_samples": 508.5, "roi_head/num_fg_samples": 3.5, "rpn/num_neg_anchors": 122.5, "rpn/num_pos_anchors": 14.5, "total_loss": 5.21594106478733}
{"fast_rcnn/cls_accuracy": 0.9775390625, "fast_rcnn/false_negative": 1.0, "fast_rcnn/fg_cls_accuracy": 0.0, "iteration": 19, "loss_box_reg": 0.04728011600673199, "loss_cls": 0.32810433208942413, "loss_rpn_cls": 0.433779239654541, "loss_rpn_loc": 0.018016567453742027, "lr": 0.0038161999999999996, "roi_head/num_bg_samples": 505.0, "roi_head/num_fg_samples": 7.0, "rpn/num_neg_anchors": 249.0, "rpn/num_pos_anchors": 7.0, "total_loss": 0.95173489023}

**Comment by MingqiangNing** [comment]
看下你这边生成的.json文件和metrics.json有什么不同，把多余的行删除掉，严格按照给的格式来。

**Comment by johnenvpath** [comment]
我发现了，是数据的问题。因为我是接着训练的所以多了两行AP、AP50、AP75的输出，这行没有"iteration"和"total_loss"
